export enum DepreciationMethod{
    STRAIGHT_LINE = 'STRAIGHT_LINE',
    DECLINING_BALANCE = 'DECLINING_BALANCE',
    DECLINING_BALANCE_150 = 'DECLINING_BALANCE_150',
    DECLINING_BALANCE_200 = 'DECLINING_BALANCE_200'
}
